security:
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt

     providers:
            our_db_provider:
                entity:
                    class: AppBundle:User
                    property: username
                    # if you're using multiple entity managers
                    # manager_name: customer

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN]

    firewalls:
            main:
                pattern:    ^/
                http_basic: ~
                provider: our_db_provider

        main:
            anonymous: ~

            logout:
              path: /logout
              target: /
            form_login:
                              login_path: login
                              check_path: login
                              default_target_path: default_security_target
                              always_use_default_target_path: true


    access_control:
        - { path: ^/luckynumber, roles: ROLE_ADMIN }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
       # - { path: ^/, roles: ROLE_ADMIN }
